In [1]:
# Importing libraries
import pandas as pd

In [2]:
# we can set numbers for how many rows and columns will be displayed
pd.set_option('display.min_rows', 10) #default will be 10
pd.set_option('display.max_columns', 20)

In [3]:
# read csv file

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data_driven_AI/online_store_customer_data.csv')
df.head(3)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60

# Task 1

In [4]:
# •	Find out the number of rows and columns in your data frame by using function shape
print("Data Shape: ", df.shape)
print("Rows in Data: ", df.shape[0])
print("Columns in Data: ", df.shape[1])

Data Shape:  (2512, 11)
Rows in Data:  2512
Columns in Data:  11

In [5]:
# •	Display the statistical summary of your data frame by using describe() function.
df.describe()

       Transaction_ID          Age      Referal  Amount_spent
count     2512.000000  2470.000000  2357.000000   2270.000000
mean    152443.931131    46.637652     0.652100   1418.422577
std        724.580482    18.186277     0.476405    878.507451
min     151200.000000    15.000000     0.000000      2.090000
25%     151815.750000    32.000000     0.000000    678.192500
50%     152443.500000    47.000000     1.000000   1341.435000
75%     153071.250000    62.000000     1.000000   2038.102500
max     153699.000000    78.000000     1.000000   2999.980000

In [6]:
# •	Use function info to find out columns, their data types, and number of non-null values in each column.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_date  2512 non-null   object
 1   Transaction_ID    2512 non-null   int64
 2   Gender            2484 non-null   object
 3   Age               2470 non-null   float64
 4   Marital_status    2512 non-null   object
 5   State_names       2512 non-null   object
 6   Segment           2512 non-null   object
 7   Employees_status  2486 non-null   object
 8   Payment_method    2512 non-null   object
 9   Referal           2357 non-null   float64
 10  Amount_spent      2270 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 216.0+ KB

In [7]:
# •	Use function value_counts() to find out unique values and their frequency in columns Gender, Marital_status, and Payement_method.
print(df['Gender'].value_counts())
print(df['Marital_status'].value_counts())
print(df['Payment_method'].value_counts())

Female    1356
Male      1128
Name: Gender, dtype: int64
Married    1473
Single     1039
Name: Marital_status, dtype: int64
PayPal    1168
Card       749
Other      595
Name: Payment_method, dtype: int64

# Task 2

In [8]:
df.isna().sum()

Transaction_date      0
Transaction_ID        0
Gender               28
Age                  42
Marital_status        0
State_names           0
Segment               0
Employees_status     26
Payment_method        0
Referal             155
Amount_spent        242
dtype: int64

In [9]:
df.isnull().sum()

Transaction_date      0
Transaction_ID        0
Gender               28
Age                  42
Marital_status        0
State_names           0
Segment               0
Employees_status     26
Payment_method        0
Referal             155
Amount_spent        242
dtype: int64

# Task 3

In [10]:
# Drop column “Amount_spent” using df.drop(‘column name’, inplace=True)
df_temp = df.copy()
df_temp.drop(columns=['Amount_spent'], inplace=True)
df_temp.head(3)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0

In [11]:
print(df_temp.isnull().sum())

Transaction_date      0
Transaction_ID        0
Gender               28
Age                  42
Marital_status        0
State_names           0
Segment               0
Employees_status     26
Payment_method        0
Referal             155
dtype: int64

In [12]:
# Remove rows from data frame where Employee_status values are missing.

df_temp.dropna(subset = ["Employees_status"], inplace=True)
df_temp.isnull().sum()

Transaction_date      0
Transaction_ID        0
Gender               27
Age                  42
Marital_status        0
State_names           0
Segment               0
Employees_status      0
Payment_method        0
Referal             154
dtype: int64

In [13]:
# Replace Amount_spent missing values with the mean value of amount_spent.
mean_AS = df['Amount_spent'].mean()
df['Amount_spent'].fillna(mean_AS, inplace=True)
df.isnull().sum()

Transaction_date      0
Transaction_ID        0
Gender               28
Age                  42
Marital_status        0
State_names           0
Segment               0
Employees_status     26
Payment_method        0
Referal             155
Amount_spent          0
dtype: int64

In [14]:
# Replace missing values in Age with the mean age value.
mean_Age = df['Age'].mean()
df['Age'].fillna(mean_Age, inplace=True)
df.isnull().sum()

Transaction_date      0
Transaction_ID        0
Gender               28
Age                   0
Marital_status        0
State_names           0
Segment               0
Employees_status     26
Payment_method        0
Referal             155
Amount_spent          0
dtype: int64

In [15]:
# Replace missing values in Referal with the mean Referal value.
mean_R = df['Referal'].mean()
df['Referal'].fillna(mean_R, inplace=True)
df.isnull().sum()

Transaction_date     0
Transaction_ID       0
Gender              28
Age                  0
Marital_status       0
State_names          0
Segment              0
Employees_status    26
Payment_method       0
Referal              0
Amount_spent         0
dtype: int64

In [16]:
# Replace missing values in “Employee_status” with the mode value of column “Employee_status”.
mode_emp = df['Employees_status'].mode().iloc[0]
df['Employees_status'].fillna(mode_emp, inplace=True)
df.isnull().sum()

Transaction_date     0
Transaction_ID       0
Gender              28
Age                  0
Marital_status       0
State_names          0
Segment              0
Employees_status     0
Payment_method       0
Referal              0
Amount_spent         0
dtype: int64

In [17]:
# Replace missing values in Gender with the mode value of column Gender.
mode_Gender = df['Gender'].mode().iloc[0]
df['Gender'].fillna(mode_Gender, inplace=True)
df.isnull().sum()

Transaction_date    0
Transaction_ID      0
Gender              0
Age                 0
Marital_status      0
State_names         0
Segment             0
Employees_status    0
Payment_method      0
Referal             0
Amount_spent        0
dtype: int64